# API CONFIGURATIONS ==============================================================================
BASE_URL: http://localhost:3000/api/v1/
CERT:

# PAGES TO SHOW ==================================================================================
PAGES_TO_SHOW:  # Set to a list of pages or "all" to show all
- Explore a Prediction
- Similar Entities
- Compare Entities
- Experiment with Changes
- Understand the Model
- Settings
BAR_LENGTH: 8  # Number of squares to use for contribution/importance bars
MAX_ENTITIES: 11 # Maximum number of entities to select from. Set this to None to use all
DATASET_SIZE: 1000 # Max number of entities to use for dataset-wide visualizations
LOAD_UPFRONT: true # If true, run heavy computations on initial load, else greedily run as needed
ALLOW_PAGE_SELECTION: false # If true, allow user to select which pages to show (requires settings page)

# APPLICATION-SPECIFIC CONFIGURATIONS (overrides API context) =====================================
FLIP_COLORS: false # deprecated (use COLOR_SCHEME) keeping for api support
COLOR_SCHEME: Standard # Standard: positive is blue. Reversed: positive is red. Neutral: Neither
PREDICTION_TYPE: # One of "numeric", "boolean", "categorical"
POSITIVE_TERM: # Term to use for a True prediction for boolean models
NEGATIVE_TERM: # Term to use for a False prediction for boolean models
PRED_FORMAT_STRING: # fstring for formatting numeric model outputs
OVERRIDE_PRED_FORMAT: # If True, use "config.manual_pred_format_func" to format preds, ignoring previous 3 configs
SUPPORT_PROBABILITY: # Only set this to True when model supports `predict_proba`
Explore a Prediction: true
Similar Entities: true
Compare Entities: true
Experiment with Changes: true
Understand the Model: true
